-- =============================================================================
-- FishingBR — Seed de dados de referência
-- Execute APÓS o schema.sql
-- Baseado nos dados de constants/mockData.ts
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Espécies de peixe
-- ON CONFLICT (name) DO NOTHING → idempotente via constraint fish_species_name_unique
-- id omitido: o banco gera o uuid via DEFAULT gen_random_uuid()
-- ---------------------------------------------------------------------------
INSERT INTO fish_species (name)
VALUES
  -- Água doce
  ('Acará'),
  ('Apapá'),
  ('Armau'),
  ('Arraia'),
  ('Aruanã'),
  ('Bagre-africano'),
  ('Barbado'),
  ('Bicuda'),
  ('Black Bass'),
  ('Cachapira'),
  ('Cachara'),
  ('Cachorra'),
  ('Caparari'),
  ('Carpa cabeçuda'),
  ('Carpa capim'),
  ('Carpa comum'),
  ('Carpa húngara'),
  ('Carpa koi'),
  ('Cascudo'),
  ('Catfish'),
  ('Corvina de água doce'),
  ('Curimba'),
  ('Dourado'),
  ('Jacundá'),
  ('Jaú'),
  ('Jundiá'),
  ('Lambari'),
  ('Mandi'),
  ('Matrinxã'),
  ('Oscar'),
  ('Pacu'),
  ('Patinga'),
  ('Piapara'),
  ('Piau'),
  ('Piavuçu'),
  ('Pincachara'),
  ('Pintado'),
  ('Piraíba'),
  ('Piranha-preta'),
  ('Piranha-vermelha'),
  ('Pirapitinga'),
  ('Piraputanga'),
  ('Pirarara'),
  ('Pirarucu'),
  ('Surubim-chicote'),
  ('Tabarana'),
  ('Tambacu'),
  ('Tambaqui'),
  ('Tambatinga'),
  ('Tilápia'),
  ('Tilápia do Nilo'),
  ('Tilápia Saint-Peter'),
  ('Traíra comum'),
  ('Traíra Tornasol'),
  ('Traírão'),
  ('Truta arco-íris'),
  ('Tucunaré Açu'),
  ('Tucunaré Amarelo'),
  ('Tucunaré Azul'),
  ('Tucunaré Paca'),
  ('Tucunaré Paca-Açu'),
  ('Tucunaré Pinima'),
  -- Água salgada
  ('Robalo-peva'),
  ('Robalo-flecha'),
  ('Tarpon'),
  ('Tainha'),
  ('Anchova'),
  ('Xaréu'),
  ('Olhete'),
  ('Garoupa'),
  ('Badejo'),
  ('Pargo'),
  ('Cioba'),
  ('Vermelho'),
  ('Caranha'),
  ('Enchova'),
  ('Cavala'),
  ('Sororoca'),
  ('Atum-amarelo'),
  ('Atum-azul'),
  ('Barracuda'),
  ('Bonito'),
  ('Dourado do mar'),
  ('Marlim'),
  ('Pampo'),
  ('Sargo'),
  ('Corvina de água salgada'),
  ('Pescada'),
  ('Linguado'),
  ('Bagre do mar'),
  ('Cação'),
  ('Ubarana'),
  ('Baiacu'),
  ('Olho-de-boi'),
  ('Cherne'),
  ('Piracanjuba')
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Iscas / Lures
-- ON CONFLICT (name, type) DO NOTHING → idempotente via constraint lures_name_type_unique
-- ---------------------------------------------------------------------------
INSERT INTO lures (name, type, description)
VALUES
  -- Iscas naturais — massa / vegetal
  ('Massa',              'natural', NULL),
  ('Ração na pinga',     'natural', NULL),
  ('Milho',              'natural', NULL),
  ('Ervilha',            'natural', NULL),
  ('Pão',                'natural', NULL),
  ('Miçanga',            'natural', NULL),
  ('Salsicha',           'natural', NULL),
  ('Queijo',             'natural', NULL),
  ('Goiabada',           'natural', NULL),
  ('Banana',             'natural', NULL),
  -- Iscas naturais — animal (terrestres)
  ('Minhoca',            'natural', NULL),
  ('Larva (tenébrio)',   'natural', NULL),
  ('Bicho da laranja',   'natural', NULL),
  ('Caranguejo',         'natural', NULL),
  ('Fígado',             'natural', NULL),
  ('Coração de frango',  'natural', NULL),
  -- Iscas naturais — peixe / fruto do mar
  ('Tilápia',            'natural', NULL),
  ('Filé de peixe',      'natural', NULL),
  ('Camarão',            'natural', NULL),
  ('Cabeça de peixe',    'natural', NULL),
  ('Pirambóia',          'natural', NULL),
  ('Lambari',            'natural', NULL),
  ('Piranha',            'natural', NULL),
  ('Corrupto',           'natural', NULL),
  ('Lula',               'natural', NULL),
  ('Polvo',              'natural', NULL),
  ('Sardinha',           'natural', NULL),
  ('Tainha',             'natural', NULL),
  ('Parati',             'natural', NULL),
  ('Manjuba',            'natural', NULL),
  ('Anchova',            'natural', NULL),
  ('Siri',               'natural', NULL),
  ('Marisco',            'natural', NULL),
  ('Mexilhão',           'natural', NULL),
  ('Berbigão',           'natural', NULL),
  ('Tatui',              'natural', NULL),
  ('Ouriço',             'natural', NULL),
  -- Iscas artificiais — superfície
  ('Popper',             'artificial', NULL),
  ('Hélice',             'artificial', NULL),
  ('Stick',              'artificial', NULL),
  ('Zara',               'artificial', NULL),
  -- Iscas artificiais — mergulhantes / crankbait
  ('Plug de meia-água',  'artificial', NULL),
  ('Plug de fundo',      'artificial', NULL),
  ('Crankbait',          'artificial', NULL),
  ('Minnow',             'artificial', NULL),
  ('Colher',             'artificial', NULL),
  -- Iscas artificiais — soft plastic
  ('Minhoca (soft)',     'artificial', NULL),
  ('Camarão (soft)',     'artificial', NULL),
  ('Shad',               'artificial', NULL),
  ('EVA',                'artificial', NULL),
  -- Iscas artificiais — metal / outros
  ('Spinner',            'artificial', NULL),
  ('Spinner shad',       'artificial', NULL),
  ('Sabiki',             'artificial', NULL),
  ('Lula artificial',    'artificial', NULL),
  -- Jig
  ('Jig',                'jig', NULL),
  ('Jighead',            'jig', NULL),
  -- Mosca
  ('Mosca (fly)',        'fly', NULL)
ON CONFLICT (name, type) DO NOTHING;
