import { User, FishingSpot, Catch, FishSpecies, UserStats } from '@/types';

export const currentUser: User = {
  id: '1',
  name: 'João Silva',
  username: 'joaosilva',
  avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
  bio: 'Pescador apaixonado pelo Pantanal',
  totalCatches: 127,
  totalSpots: 15,
  joinedDate: '2023-01-15',
};

export const users: User[] = [
  currentUser,
  {
    id: '2',
    name: 'Maria Santos',
    username: 'mariasantos',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
    bio: 'Pesca esportiva há 10 anos',
    totalCatches: 203,
    totalSpots: 28,
    joinedDate: '2022-08-20',
  },
  {
    id: '3',
    name: 'Carlos Oliveira',
    username: 'carlosoliveira',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=400',
    bio: 'Amazônia é minha casa',
    totalCatches: 89,
    totalSpots: 12,
    joinedDate: '2023-03-10',
  },
];

export const fishingSpots: FishingSpot[] = [
  {
    id: '1',
    name: 'Rio Tietê - Barra Bonita',
    location: {
      lat: -22.4967,
      lng: -48.5578,
      city: 'Barra Bonita',
      state: 'SP',
    },
    type: 'river',
    rating: 4.5,
    totalCatches: 234,
    description: 'Excelente local para pesca de tilápias e carpas',
    addedBy: users[1],
    photos: ['https://images.pexels.com/photos/1007426/pexels-photo-1007426.jpeg?auto=compress&cs=tinysrgb&w=800'],
  },
  {
    id: '2',
    name: 'Represa Billings',
    location: {
      lat: -23.7833,
      lng: -46.5667,
      city: 'São Bernardo do Campo',
      state: 'SP',
    },
    type: 'reservoir',
    rating: 4.2,
    totalCatches: 156,
    description: 'Grande represa com diversas espécies',
    addedBy: currentUser,
    photos: ['https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=800'],
  },
  {
    id: '3',
    name: 'Pantanal - Porto Jofre',
    location: {
      lat: -17.4333,
      lng: -56.7833,
      city: 'Poconé',
      state: 'MT',
    },
    type: 'river',
    rating: 5.0,
    totalCatches: 412,
    description: 'Paraíso da pesca esportiva, pintados e pacus gigantes',
    addedBy: users[2],
    photos: ['https://images.pexels.com/photos/1578750/pexels-photo-1578750.jpeg?auto=compress&cs=tinysrgb&w=800'],
  },
  {
    id: '4',
    name: 'Lagoa Rodrigo de Freitas',
    location: {
      lat: -22.9667,
      lng: -43.2083,
      city: 'Rio de Janeiro',
      state: 'RJ',
    },
    type: 'lake',
    rating: 3.8,
    totalCatches: 87,
    description: 'Lagoa urbana com boa infraestrutura',
    addedBy: users[1],
    photos: ['https://images.pexels.com/photos/2166711/pexels-photo-2166711.jpeg?auto=compress&cs=tinysrgb&w=800'],
  },
  {
    id: '5',
    name: 'Praia de Copacabana',
    location: {
      lat: -22.9711,
      lng: -43.1822,
      city: 'Rio de Janeiro',
      state: 'RJ',
    },
    type: 'ocean',
    rating: 4.0,
    totalCatches: 198,
    description: 'Pesca de praia, robalos e corvinas',
    addedBy: users[2],
    photos: ['https://images.pexels.com/photos/1483880/pexels-photo-1483880.jpeg?auto=compress&cs=tinysrgb&w=800'],
  },
  {
    id: '6',
    name: 'Rio Amazonas - Manaus',
    location: {
      lat: -3.1190,
      lng: -60.0217,
      city: 'Manaus',
      state: 'AM',
    },
    type: 'river',
    rating: 4.9,
    totalCatches: 523,
    description: 'O maior rio do mundo, tucunarés e pirarucus',
    addedBy: users[2],
    photos: ['https://images.pexels.com/photos/975771/pexels-photo-975771.jpeg?auto=compress&cs=tinysrgb&w=800'],
  },
];

export const catches: Catch[] = [
  {
    id: '1',
    user: users[1],
    species: 'Tucunaré Açu',
    weight: 8.5,
    length: 65,
    bait: 'Isca artificial - Stick',
    location: {
      lat: -3.1190,
      lng: -60.0217,
      name: 'Rio Amazonas - Manaus',
    },
    photo: 'https://images.pexels.com/photos/1363995/pexels-photo-1363995.jpeg?auto=compress&cs=tinysrgb&w=800',
    notes: 'Que pescaria incrível! Depois de 20 minutos brigando.',
    date: '2024-03-08T14:30:00',
    likes: 45,
    comments: 12,
    isLiked: false,
  },
  {
    id: '2',
    user: users[2],
    species: 'Pintado',
    weight: 15.2,
    length: 95,
    bait: 'Peixe vivo - Lambari',
    location: {
      lat: -17.4333,
      lng: -56.7833,
      name: 'Pantanal - Porto Jofre',
    },
    photo: 'https://images.pexels.com/photos/1078058/pexels-photo-1078058.jpeg?auto=compress&cs=tinysrgb&w=800',
    notes: 'Meu maior pintado até hoje! O Pantanal é mágico.',
    date: '2024-03-07T09:15:00',
    likes: 89,
    comments: 23,
    isLiked: true,
  },
  {
    id: '3',
    user: currentUser,
    species: 'Robalo',
    weight: 3.8,
    length: 52,
    bait: 'Camarão vivo',
    location: {
      lat: -22.9711,
      lng: -43.1822,
      name: 'Praia de Copacabana',
    },
    photo: 'https://images.pexels.com/photos/1374510/pexels-photo-1374510.jpeg?auto=compress&cs=tinysrgb&w=800',
    notes: 'Pescaria urbana de manhã cedo',
    date: '2024-03-06T06:45:00',
    likes: 67,
    comments: 8,
    isLiked: false,
  },
  {
    id: '4',
    user: users[1],
    species: 'Traíra',
    weight: 2.1,
    bait: 'Minhoca',
    location: {
      lat: -22.4967,
      lng: -48.5578,
      name: 'Rio Tietê - Barra Bonita',
    },
    photo: 'https://images.pexels.com/photos/1125776/pexels-photo-1125776.jpeg?auto=compress&cs=tinysrgb&w=800',
    notes: 'Pescaria tranquila de fim de tarde',
    date: '2024-03-05T17:20:00',
    likes: 34,
    comments: 5,
    isLiked: true,
  },
  {
    id: '5',
    user: users[2],
    species: 'Pirarucu',
    weight: 42.0,
    length: 185,
    bait: 'Peixe vivo',
    location: {
      lat: -3.1190,
      lng: -60.0217,
      name: 'Rio Amazonas - Manaus',
    },
    photo: 'https://images.pexels.com/photos/1374510/pexels-photo-1374510.jpeg?auto=compress&cs=tinysrgb&w=800',
    notes: 'Sensacional! Um dos peixes mais incríveis da Amazônia.',
    date: '2024-03-04T11:30:00',
    likes: 156,
    comments: 34,
    isLiked: false,
  },
  {
    id: '6',
    user: currentUser,
    species: 'Dourado',
    weight: 12.5,
    length: 78,
    bait: 'Isca artificial - Jig',
    location: {
      lat: -17.4333,
      lng: -56.7833,
      name: 'Pantanal - Porto Jofre',
    },
    photo: 'https://images.pexels.com/photos/5799896/pexels-photo-5799896.jpeg?auto=compress&cs=tinysrgb&w=800',
    notes: 'Dourado deu um show de saltos!',
    date: '2024-03-03T08:00:00',
    likes: 92,
    comments: 15,
    isLiked: true,
  },
];

export const fishSpecies: FishSpecies[] = [
  {
    id: '1',
    name: 'Tucunaré',
    scientificName: 'Cichla spp.',
    image: 'https://images.pexels.com/photos/1363995/pexels-photo-1363995.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Peixe esportivo muito popular na Amazônia',
    averageWeight: '3-8 kg',
    habitat: ['Rios', 'Lagos', 'Represas'],
    popularBaits: ['Isca artificial', 'Peixe vivo'],
  },
  {
    id: '2',
    name: 'Pintado',
    scientificName: 'Pseudoplatystoma corruscans',
    image: 'https://images.pexels.com/photos/1078058/pexels-photo-1078058.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Peixe de couro muito apreciado',
    averageWeight: '10-20 kg',
    habitat: ['Rios'],
    popularBaits: ['Peixe vivo', 'Pedaços de peixe'],
  },
  {
    id: '3',
    name: 'Dourado',
    scientificName: 'Salminus brasiliensis',
    image: 'https://images.pexels.com/photos/5799896/pexels-photo-5799896.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'O rei do rio, lutador poderoso',
    averageWeight: '5-15 kg',
    habitat: ['Rios'],
    popularBaits: ['Isca artificial', 'Peixe vivo'],
  },
  {
    id: '4',
    name: 'Pirarucu',
    scientificName: 'Arapaima gigas',
    image: 'https://images.pexels.com/photos/1374510/pexels-photo-1374510.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Maior peixe de água doce da Amazônia',
    averageWeight: '100-150 kg',
    habitat: ['Rios', 'Lagos'],
    popularBaits: ['Peixe vivo'],
  },
  {
    id: '5',
    name: 'Robalo',
    scientificName: 'Centropomus spp.',
    image: 'https://images.pexels.com/photos/1374510/pexels-photo-1374510.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Peixe costeiro muito esportivo',
    averageWeight: '2-6 kg',
    habitat: ['Oceano', 'Estuários'],
    popularBaits: ['Camarão', 'Isca artificial'],
  },
  {
    id: '6',
    name: 'Traíra',
    scientificName: 'Hoplias malabaricus',
    image: 'https://images.pexels.com/photos/1125776/pexels-photo-1125776.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Predador voraz encontrado em todo Brasil',
    averageWeight: '1-3 kg',
    habitat: ['Rios', 'Lagos', 'Represas'],
    popularBaits: ['Minhoca', 'Peixe vivo', 'Isca artificial'],
  },
];

export const userStats: UserStats = {
  totalCatches: 127,
  totalSpecies: 18,
  totalWeight: 342.5,
  biggestCatch: {
    species: 'Pintado',
    weight: 18.2,
    date: '2024-01-15',
  },
  recentActivity: {
    thisWeek: 3,
    thisMonth: 12,
  },
};
